#!/bin/zsh

if [ "$1" = '' ]; then
	echo "Please set directory name!"
	exit 1
fi

if [ ! -e test.cpp ]; then
	echo "test.cpp does not exist!"
	exit 1
fi

if [ -d "./$1" ]; then
	echo "The directory name is already set!"
	exit 1
fi

mkdir "$1"
echo "$1 was just made!"
cp test.cpp "./$1/a.cpp"
cp test.cpp "./$1/b.cpp"
cp test.cpp "./$1/c.cpp"
cp test.cpp "./$1/d.cpp"
cp test.cpp "./$1/d.cpp"
cp test.cpp "./$1/e.cpp"
cp test.cpp "./$1/f.cpp"
